### ISSUE TITLE
High use of the Plex API Sign In

### ISSUE THREAD

**Issue by jseravalli** [d4rk22/Network-Status-Page#2]
I'm a developer for Plex, recently we've been tracking login events and noticed that users using this code are requesting a token from our API at a really high rate, some have 180,000 requests in less than four days. Because of this we wanted to reach out and ask for a few changes: 
- Change the `X-Plex-Client-Identifier` to a universally unique identifier. Or to something resembling a unique string.
- Cache the `X-Plex-Token` to reduce the number of times it hits our sign in API endpoint.
- Add the `X-Plex-Product` header with a string that identifies this product.

We may limit the number of times a user without the `X-Plex-Product` or with a same `X-Plex-Client-Identifier` header can make login attempts to our API, so please take measures to prevent any harm to the users of this product. 

If you need any help, I will be available through this GHI or you can open a new discussion in our forums in the [Plex TV Services](https://forums.plex.tv/categories/plextv-services) section.

Thanks,
Jose

**Comment by d4rk22** [comment]
I haven’t touched the code in a year or two but I can dust it off and make those requested changes and then make a post to the forum as well to let users know to update their code.

Ryan Christensen

**Comment by jseravalli** [comment]
Thank you, for the fast response and for taking action.

Please don't hesitate on reaching out if you need more information.

**Comment by d4rk22** [comment]
I got this working. Turns out that I had already written a caching function but it was broken. I should really write more unit tests.

In the new version I'm caching the Plex token for a week. How does that sound for a time frame?

**Comment by jseravalli** [comment]
Great! A week sounds good, or if you want you can keep the token until it no longer auths.

**Comment by d4rk22** [comment]
I'm now caching the Plex tokens unless they fail and only then fetching a new one. Just to clarify, are the values below ideal values for the request headers?

-H "X-Plex-Client-Identifier: 365f1969-da53-411a-ad52-9c82437dcd58" -H "X-Plex-Product: Network-Status-Page"

**Comment by d4rk22** [comment]
This has been resolved in version 0.2.1 and an update posted to the forums.

**Comment by jseravalli** [comment]
I got a notification about the client identifier and the product name, they both looked good. Thank you for this!
