### ISSUE TITLE
is this still under development?

### ISSUE THREAD

**Issue by seanvree** [d4rk22/Network-Status-Page#6]
I see a few forks out there, but none seem to be active.  This is a great project! Just wondering if there is another project out there that is active.

**Comment by d4rk22** [comment]
I am not actively developing it. What are you looking for? I've been toying around with rewriting it in a modern language but there are already quote a few alternatives out there now.

**Comment by seanvree** [comment]
@d4rk22  - I'm looking for a solution that provides exactly this.  

I simply would like a one-page status monitoring for my plex tools.

This is exactly what I'd like! Not sure why no one is developing it anymore?  I sure as hell haven't found a good replcaement.  

I'm a python and windows guru, so if you'd like to revive, I could help. 

Also, it looks like someone else picked up the project and got pretty far, but again, fell off:

https://github.com/scytherswings/Network-Status-Page

**Comment by d4rk22** [comment]
@seanvree What system would you be running it on? If I picked this back up I would probably run it and test it on Ubuntu with apache.

**Comment by seanvree** [comment]
Windows with IIS.  But I can make that work, just as long as it isn't designed for OSx.  

I mean, if we picked the project back up we could make it work for both ubuntu and windows with slight modification if we use PHP.

**Comment by seanvree** [comment]
@d4rk22 just FYI, we've picked this project back up.  I've got it working on windows and we're cleaning some things up.  You're welcome to help out....or not.  HA

https://github.com/scytherswings/Plex-Board
